const codingBoard = $("#coding-board");
const codingStatus = $("#coding-status");
const codingLevelButtons = $$('[data-coding-level]');
const commandButtons = $$('[data-command]');
const programTimeline = $("#program-timeline");
const programCount = $("#program-count");
const codingRun = $("#coding-run"), codingClear=$("#coding-clear"), codingUndo=$("#coding-undo"), newCodingPuzzle=$("#new-coding-puzzle"), codingWinOverlay=$("#coding-win-overlay"), codingWinStars=$("#coding-win-stars"), codingWinText=$("#coding-win-text");
const levelInfo={easy:{rows:5,cols:5,min:5,open:8,crate:false,max:18},medium:{rows:6,cols:6,min:8,open:5,crate:true,max:25},hard:{rows:7,cols:7,min:11,open:2,crate:true,max:32}};
const dirs=[[-1,0],[0,1],[1,0],[0,-1]];
const glyph={forward:'↑',back:'↓',left:'↶',right:'↷',action:'◆'};
let codingLevel=localStorage.getItem('codingLevel')||'easy', puzzle=null, program=[], running=false, token=0;
const key=(r,c)=>`${r},${c}`, info=()=>levelInfo[codingLevel];
function inBounds(r,c){return r>=0&&r<info().rows&&c>=0&&c<info().cols}
function blocked(r,c){return puzzle.obstacles.has(key(r,c))}
function stepState(st,cmd){let s={...st}; if(cmd==='left'){s.dir=(s.dir+3)%4;return s} if(cmd==='right'){s.dir=(s.dir+1)%4;return s} if(cmd==='action'){if(!info().crate)return {...s,invalid:true}; if(!s.carrying&&!s.delivered&&s.row===puzzle.crate.row&&s.col===puzzle.crate.col){s.carrying=true;return s} if(s.carrying&&s.row===puzzle.drop.row&&s.col===puzzle.drop.col){s.carrying=false;s.delivered=true;return s} return {...s,invalid:true};} const [dr,dc]=dirs[s.dir], sign=cmd==='back'?-1:1, nr=s.row+dr*sign,nc=s.col+dc*sign; if(!inBounds(nr,nc)||blocked(nr,nc)) return {...s,collision:true}; s.row=nr;s.col=nc;return s}
function shortest(p){const st={row:p.start.row,col:p.start.col,dir:0,carrying:false,delivered:!info().crate}; const q=[{s:st,path:[]}],seen=new Set; while(q.length){let {s,path}=q.shift(), sk=`${s.row},${s.col},${s.dir},${+s.carrying},${+s.delivered}`; if(seen.has(sk))continue;seen.add(sk); if(s.row===p.goal.row&&s.col===p.goal.col&&s.delivered)return path; for(const c of ['forward','back','left','right',...(info().crate?['action']:[])]){let n=stepStateForPuzzle(s,c,p);if(!n.collision&&!n.invalid)q.push({s:n,path:[...path,c]})}} return null}
function stepStateForPuzzle(st,cmd,p){let old=puzzle;puzzle=p;let n=stepState(st,cmd);puzzle=old;return n}
function makeRoute(start,goal,minCells){let path=[{...start}],vis=new Set([key(start.row,start.col)]);function dfs(r,c){if(r===goal.row&&c===goal.col&&path.length>=minCells)return true;let a=[[-1,0],[0,1],[1,0],[0,-1]].map(([dr,dc])=>({row:r+dr,col:c+dc})).filter(x=>inBounds(x.row,x.col)&&!vis.has(key(x.row,x.col))&&(x.row!==0||(x.row===goal.row&&x.col===goal.col))).sort(()=>Math.random()-.5);for(let n of a){vis.add(key(n.row,n.col));path.push(n);if(dfs(n.row,n.col))return true;path.pop();vis.delete(key(n.row,n.col))}return false}return dfs(start.row,start.col)?path:null}
function buildCandidate(){let I=info(),start={row:I.rows-1,col:Math.floor(Math.random()*I.cols)},goal={row:0,col:Math.floor(Math.random()*I.cols)};let route=makeRoute(start,goal,I.min);if(!route)return null;let routeSet=new Set(route.map(x=>key(x.row,x.col))), obstacles=new Set;for(let r=0;r<I.rows;r++)for(let c=0;c<I.cols;c++)if(!routeSet.has(key(r,c)))obstacles.add(key(r,c));[...obstacles].sort(()=>Math.random()-.5).slice(0,I.open).forEach(k=>obstacles.delete(k));let p={start,goal,obstacles}; if(I.crate){let a=Math.max(1,Math.floor(route.length*.3)), b=Math.min(route.length-2,Math.floor(route.length*.68));p.crate={...route[a]};p.drop={...route[b]};} puzzle=p;let sol=shortest(p); if(!sol||sol.length>I.max)return null;p.solution=sol;return p}
function newPuzzle(){token++;running=false;program=[];codingWinOverlay.classList.add('hidden');for(let i=0;i<500&&!puzzle;i++)puzzle=buildCandidate();if(!puzzle){puzzle={start:{row:info().rows-1,col:1},goal:{row:0,col:info().cols-2},obstacles:new Set}; if(info().crate){puzzle.crate={row:info().rows-2,col:1};puzzle.drop={row:1,col:info().cols-2}} puzzle.solution=shortest(puzzle)||[];} reset(false); codingStatus.textContent=info().crate?'Move the crate to the delivery square, then reach the finish.':'Guide the forklift to the finish.'; renderBoard();renderProgram();setEnabled(true); puzzle._fresh=false}
function reset(render=true){puzzle.state={row:puzzle.start.row,col:puzzle.start.col,dir:0,carrying:false,delivered:!info().crate};if(render)renderBoard()}
function forkliftSvg(){return `<svg viewBox="0 0 64 64"><path d="M8 38h34l7 10H15zM16 38V22h18v16M34 27h8l7 11M22 22V13h15M49 20v28M49 43h9M17 48a6 6 0 1 0 0 12 6 6 0 0 0 0-12zM43 48a6 6 0 1 0 0 12 6 6 0 0 0 0-12z"/></svg>`}
function renderBoard(){let I=info();codingBoard.style.setProperty('--coding-rows',I.rows);codingBoard.style.setProperty('--coding-cols',I.cols);codingBoard.innerHTML='';for(let r=0;r<I.rows;r++)for(let c=0;c<I.cols;c++){let el=document.createElement('div');el.className='grid-cell';if(puzzle.obstacles.has(key(r,c)))el.classList.add('obstacle');if(r===puzzle.goal.row&&c===puzzle.goal.col){el.classList.add('goal-cell');el.innerHTML='<span class="finish-mark"><svg viewBox="0 0 32 32"><path d="M8 28V5M9 6h14l-3 5 3 5H9"/></svg></span>'}if(info().crate&&!puzzle.state.delivered&&!puzzle.state.carrying&&r===puzzle.crate.row&&c===puzzle.crate.col)el.innerHTML+='<span class="coding-crate"></span>';if(info().crate&&r===puzzle.drop.row&&c===puzzle.drop.col)el.innerHTML+='<span class="coding-drop"></span>';codingBoard.appendChild(el)}let rover=document.createElement('div');rover.id='coding-rover';rover.className='coding-forklift';rover.innerHTML= forkliftSvg()+(puzzle.state.carrying?'<span class="carried-crate"></span>':'');codingBoard.appendChild(rover);positionRover(false)}
function positionRover(anim=true){let rover=$("#coding-rover");if(!rover)return;rover.classList.toggle('animate',anim);let x=(puzzle.state.col+.5)*100/info().cols,y=(puzzle.state.row+.5)*100/info().rows, rot=puzzle.state.dir*90;rover.style.left=x+'%';rover.style.top=y+'%';rover.style.transform=`translate(-50%,-50%) rotate(${rot}deg)`}
function renderProgram(active=-1,done=-1){programCount.textContent=program.length;programTimeline.innerHTML='';if(!program.length){programTimeline.innerHTML='<span class="program-empty">Tap a command below</span>';return}program.forEach((c,i)=>{let e=document.createElement('span');e.className='program-step';e.textContent=glyph[c];if(i===active)e.classList.add('running');else if(i<=done)e.classList.add('done');programTimeline.appendChild(e)})}
function add(c){if(running||program.length>=32)return;program.push(c);renderProgram();}
function setEnabled(v){commandButtons.forEach(b=>{b.disabled=!v;b.hidden=(b.dataset.command==='action'&&!info().crate)});[codingUndo,codingClear,codingRun,newCodingPuzzle,...codingLevelButtons].forEach(b=>b.disabled=!v)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){if(running||!program.length)return;running=true;let t=++token;setEnabled(false);reset(false);renderBoard();let done=-1;for(let i=0;i<program.length;i++){if(t!==token)return;renderProgram(i,done);let c=program[i],n=stepState(puzzle.state,c);if(n.collision||n.invalid){codingStatus.textContent=n.collision?'The forklift cannot drive there.':'Pick up or drop only on the marked square.';await wait(500);running=false;reset();renderProgram();setEnabled(true);return}puzzle.state=n;let rover=$("#coding-rover");if(c==='left'||c==='right'){positionRover(true);await wait(430)}else if(c==='action'){renderBoard();await wait(430)}else{positionRover(true);await wait(520)}done=i;if(puzzle.state.row===puzzle.goal.row&&puzzle.state.col===puzzle.goal.col&&puzzle.state.delivered){finish(i+1);return}}renderProgram(-1,done);codingStatus.textContent=info().crate&&!puzzle.state.delivered?'The crate still needs delivering.':'Not at the finish yet.';await wait(500);running=false;reset();renderProgram();setEnabled(true)}
function finish(used){running=false;renderProgram(-1,used-1);codingStatus.textContent='Challenge complete!';let extra=used-puzzle.solution.length,stars=extra<=1?3:extra<=4?2:1;codingWinStars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);codingWinText.textContent=extra<=0?'Perfect program!':`${used} commands`;codingWinOverlay.classList.remove('hidden');setEnabled(true)}
commandButtons.forEach(b=>b.addEventListener('click',()=>add(b.dataset.command)));codingUndo.addEventListener('click',()=>{if(!running){program.pop();renderProgram()}});codingClear.addEventListener('click',()=>{if(!running){program=[];renderProgram();reset()}});codingRun.addEventListener('click',run);newCodingPuzzle.addEventListener('click',()=>{puzzle=null;newPuzzle()});codingLevelButtons.forEach(b=>b.addEventListener('click',()=>{if(running)return;codingLevel=b.dataset.codingLevel;localStorage.setItem('codingLevel',codingLevel);codingLevelButtons.forEach(x=>x.classList.toggle('active',x===b));puzzle=null;newPuzzle()}));codingLevelButtons.forEach(b=>b.classList.toggle('active',b.dataset.codingLevel===codingLevel));newPuzzle();
