const realmStory=$("#realm-story"),realmQuestion=$("#realm-question"),realmDisplay=$("#realm-answer-display"),realmFeedback=$("#realm-feedback"),realmVoice=$("#realm-voice");
const realmCats=$$("[data-realm-category]"),realmLevels=$$("[data-realm-level]");let realmCategory="money",realmLevel="easy",realmCurrent,realmDigits="";
const names=["Sam","Mia","Leo","Ava","Noah","Ruby","Ben","Ella","Jack","Sophie"],pick=a=>a[Math.floor(Math.random()*a.length)],money=p=>`£${(p/100).toFixed(2)}`;
function makeMoney(l){const n=pick(names),shops=[["bookshop",[["comic",175],["notebook",240],["pen",65],["sticker pack",90]]],["café",[["juice",140],["toast",180],["cake",125],["fruit pot",95]]],["toy shop",[["ball",350],["puzzle",425],["cards",275],["kite",550]]]];let [place,items]=pick(shops),a=pick(items),b=pick(items.filter(x=>x!==a));if(l==="easy"){let total=a[1]+b[1];return Math.random()<.5?{story:`${n} buys a ${a[0]} for ${money(a[1])} and a ${b[0]} for ${money(b[1])} at the ${place}.`,question:"How much do they cost altogether?",answer:total,kind:"money"}:{story:`${n} has £5.00 and buys a ${a[0]} for ${money(a[1])}.`,question:`How much money does ${n} have left?`,answer:500-a[1],kind:"money"}}if(l==="medium"){let price=pick([135,165,225,275,320,375]),cash=pick([500,1000]);return Math.random()<.5?{story:`${n} buys two ${a[0]}s. Each one costs ${money(price)}.`,question:"How much do they cost altogether?",answer:price*2,kind:"money"}:{story:`${n} pays with ${money(cash)} for something costing ${money(price)}.`,question:"How much change should they get?",answer:cash-price,kind:"money"}}let prices=[pick([125,175,225,275]),pick([140,190,240,290]),pick([65,85,95])],total=prices.reduce((a,b)=>a+b,0);return Math.random()<.5?{story:`At a school fair, ${n} buys three things costing ${money(prices[0])}, ${money(prices[1])} and ${money(prices[2])}.`,question:"What is the total cost?",answer:total,kind:"money"}:{story:`${n} has £10.00. They spend ${money(prices[0])} and then ${money(prices[1])}.`,question:"How much money is left?",answer:1000-prices[0]-prices[1],kind:"money"}}
function makeCooking(l){const n=pick(names);if(l==="easy"){let each=pick([50,100,150,200]),count=pick([2,3,4]);return{story:`${n} is making ${count} pizzas. Each pizza needs ${each} g of cheese.`,question:"How many grams of cheese are needed altogether?",answer:each*count,kind:"g"}}if(l==="medium"){let start=pick([500,750,1000]),used=pick([150,200,250,300]);return{story:`A bag contains ${start} g of flour. ${n} uses ${used} g for baking.`,question:"How many grams of flour are left?",answer:start-used,kind:"g"}}let each=pick([125,150,175,200]),count=pick([3,4,5]);return{story:`One batch of biscuits needs ${each} g of flour. ${n} wants to make ${count} batches.`,question:"How many grams of flour are needed?",answer:each*count,kind:"g"}}
function makeDistance(l){const n=pick(names);if(l==="easy"){let a=pick([100,200,300,400]),b=pick([100,200,300]);return{story:`${n} walks ${a} m to the playground and then ${b} m to a friend's house.`,question:"How far do they walk altogether?",answer:a+b,kind:"m"}}if(l==="medium"){let total=pick([1000,1200,1500]),done=pick([300,400,500,600]);return{story:`A walking trail is ${total} m long. ${n} has already walked ${done} m.`,question:"How many metres are left?",answer:total-done,kind:"m"}}let km=pick([2,3,4]),m=pick([250,500,750]);return{story:`${n} cycles ${km} km and then another ${m} m.`,question:"How far is that altogether in metres?",answer:km*1000+m,kind:"m"}}
function makeTime(l){const n=pick(names);if(l==="easy"){let start=pick([3,4,5]),dur=pick([15,30,45]);return{story:`${n}'s club starts at ${start}:00 and lasts ${dur} minutes.`,question:"How many minutes does the club last?",answer:dur,kind:"min"}}if(l==="medium"){let h=pick([1,2]),m=pick([15,30,45]);return{story:`A journey takes ${h} hour${h>1?"s":""} and ${m} minutes.`,question:"How many minutes is the journey altogether?",answer:h*60+m,kind:"min"}}let start=pick(["09:20","10:35","13:15"]),dur=pick([40,50,75,90]);return{story:`A film starts at ${start} and lasts ${dur} minutes.`,question:"How many minutes long is the film?",answer:dur,kind:"min"}}
function formatAnswer(){if(realmCurrent?.kind==="money"){const p=Number(realmDigits||0);return money(p)}return realmDigits?`${realmDigits} ${realmCurrent?.kind||""}`:`— ${realmCurrent?.kind||""}`}
function generateRealm(){if("speechSynthesis"in window)speechSynthesis.cancel();realmCurrent=({money:makeMoney,cooking:makeCooking,distance:makeDistance,time:makeTime})[realmCategory](realmLevel);realmStory.textContent=realmCurrent.story;realmQuestion.textContent=realmCurrent.question;realmDigits="";realmDisplay.textContent=formatAnswer();realmFeedback.className="realm-feedback";realmFeedback.textContent=""}
function digit(d){if(realmDigits.length<6){realmDigits=(realmDigits+d).replace(/^0+(?=\d)/,"");realmDisplay.textContent=formatAnswer()}}
function checkRealm(){const v=Number(realmDigits||NaN),ok=Number.isFinite(v)&&v===realmCurrent.answer;realmFeedback.className=`realm-feedback ${ok?"good":"bad"}`;realmFeedback.textContent=ok?"That’s right! ★":"Not quite — have another go."}
$$('[data-realm-digit]').forEach(b=>{let handled=false;b.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){handled=true;e.preventDefault();digit(b.dataset.realmDigit)}});b.addEventListener('click',()=>{if(handled){handled=false;return}digit(b.dataset.realmDigit)})});
const realmClear=$("#realm-clear");
function clearRealmDigit(){realmDigits=realmDigits.slice(0,-1);realmDisplay.textContent=formatAnswer()}
{let handled=false;realmClear.addEventListener("pointerdown",e=>{if(e.pointerType==="touch"||e.pointerType==="pen"){handled=true;e.preventDefault();clearRealmDigit()}});realmClear.addEventListener("click",()=>{if(handled){handled=false;return}clearRealmDigit()})}
$("#realm-check").addEventListener("click",checkRealm);
realmCats.forEach(b=>b.addEventListener("click",()=>{realmCategory=b.dataset.realmCategory;realmCats.forEach(x=>x.classList.toggle("active",x===b));generateRealm()}));realmLevels.forEach(b=>b.addEventListener("click",()=>{realmLevel=b.dataset.realmLevel;realmLevels.forEach(x=>x.classList.toggle("active",x===b));generateRealm()}));$("#realm-new").addEventListener("click",generateRealm);
function loadVoices(){if(!realmVoice)return;let vs=speechSynthesis.getVoices().filter(v=>/^en(-|_)/i.test(v.lang));realmVoice.innerHTML='';vs.forEach((v,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`${v.name} (${v.lang})`;realmVoice.appendChild(o)})}if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}
$("#realm-speak").addEventListener("click",()=>{if(!realmCurrent||!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${realmCurrent.story} ${realmCurrent.question}`),vs=speechSynthesis.getVoices().filter(v=>/^en(-|_)/i.test(v.lang));if(vs[Number(realmVoice.value)])u.voice=vs[Number(realmVoice.value)];u.rate=.85;speechSynthesis.speak(u)});generateRealm();
